### ISSUE TITLE
[Feat] View 작업 (방 만들기 / 참여코드 입력 / 대기실) + GameKit

### ISSUE THREAD

**Issue by Jhwan2** [DeveloperAcademy-POSTECH/MC3-Team1-SixTech#10]
### 📝 작업할 내용 요약
[Feat] View 작업 (방 만들기 / 참여코드 입력 / 대기실) + GameKit

[Feat] View 작업 (방 만들기 / 참여코드 입력 / 대기실) + GameKit
---

### 🛠️ Tasks

* [x] EngagementView 그리기
* [x] CreateRoomView 그리기
* [x] WaitingRoomView 그리기
* [x] PloggingPlayView 그리기
* [x] MainView 그리기
* [x] GameKit 사람매칭기능
* [x] GameKit 데이터 송수신기능
* [x] GameKit 참여코드 작업
* [x] 제리가 그린뷰 플로우 연결
* [x] GameKit 기능 연결( 참여코드 기반 매칭 및 대기실 기능)
* [x] MyHistoryView 그리기
* [ ] MyProfileView 그리기
### 참고 이미지
<!-- <img src="이미지주소.png" width="200" height="400"/> >>
<!-- <img src="이미지주소.png" width="40%"/> >>
