### ISSUE TITLE
[Feat] ML과 Watch를 비벼서 쓰레기 줍기 카운트값 판별해보기 TEST.

### ISSUE THREAD

**Issue by 220v-K** [DeveloperAcademy-POSTECH/MC3-Team1-SixTech#12]
### 📝 작업할 내용 요약
CreateML & CoreML 등을 이용한 모델 생성 및 학습, 적용 공부
WatchOS의 가속도 센서를 이용한 가속도값or회전각가속도or절대 변위값을 측정.
트레이닝 데이터셋 많이많이 뽑아내기. (어떤 기준으로 데이터셋을 만들 것인지...생각)
이를 이용해 모델 생성 및 학습시키기.
측정한 모델을 이용해 테스트 및 과적합 보완 등.~
최종 적용.

---

### 🛠️ Tasks

* [x] CreateML & CoreML 등을 이용한 모델 생성 및 학습, 적용 공부
* [x] WatchOS의 가속도 센서를 이용한 가속도값 / 회전각가속도 측정
* [x] 트레이닝 데이터셋을 뽑아낼 기준 확정
* [x] 데이터셋을 뽑아내기 위한 기능 구현
* [x] Parameter 확정(batch size, epoch) 및 전체 데이터 개수 등 Jason의 조언을 통한 확정
* [x] 데이터셋 만들기 (Class별 101개씩 모음. 내 허리 박살나겟다.)
* [x] 모델 생성 및 학습시켜보기
* [x] 실제 여러 데이터로 테스트
* [x] 현 프로젝트에 CoreML로 모델 불러와 판별하는 기능 구현
* [x] 생성된 모델 테스트 및 underfitting&overfitting 보완
* [x] 최종 적용

### 참고 이미지
![happycat](https://github.com/DeveloperAcademy-POSTECH/MC3-Team1-SixTech/assets/82885362/e55581f6-3057-4821-8451-4f80b5f53886)

<!-- <img src="이미지주소.png" width="200" height="400"/> >>
<!-- <img src="이미지주소.png" width="40%"/> >>
