### ISSUE TITLE
[Feat] 플로깅중 화면 작업

### ISSUE THREAD

**Issue by JJunghyunY** [DeveloperAcademy-POSTECH/MC3-Team1-SixTech#3]
### 📝 작업할 내용 요약

플로깅 중의 메인 화면을 작업 합니다.

---

### 🛠️ Tasks

* [x] PloggingMainView 작업 (MapKit)
* [x]  Map 기능 개발(현재위치)
* [x] 맵 위의 PolyLine
* [x] Info: 걸음수, 쓰레기 줍기 횟수, 걸은 거리
+-WatchOS 연동

**Additional context**
