### ISSUE TITLE
[Feat] 온보딩 화면 작업

### ISSUE THREAD

**Issue by Oreo-Mcflurry** [DeveloperAcademy-POSTECH/MC3-Team1-SixTech#4]
### 📝 작업할 내용 요약

온보딩 화면을 작업할건데, 그 전에 앱의 버튼이 다 똑같아서 수정 및 활용이 편하도록 재사용이 가능하게 ButtonStyle을 만들어보고자 합니다.
그리고 색깔도 Color Extension을 활용하여 우리 앱의 DefaultColor(청록색)등 추가할 예정입니다.
---

### 🛠️ Tasks

* [x] Color Extension 만들기
* [x] Button Style 만들기
* [x] 온보딩 화면 만들기
* [x] 진행시켜!

**Additional context**
